version: "3.5"
services:
  front-end:
    image: "${repository}/entropy-task" 
    ports:
#      - "80:80"
      - "443:443"
    restart: no
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl/:/root/ssl/:ro
